title: 🏅 Summer Olympics 2026
markdown: GFM
theme: minima

collections:
  events:
    output: true
    permalink: /events/:path/
  awards:
    output: true
    permalink: /awards/:path.html

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "awards"
    values:
      layout: "award"
