title: 🏅 Summer Olympics 2026
markdown: GFM
theme: minima

collections:
  events:
    output: true
    permalink: /events/:path/

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
